services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6673:6673
    volumes:
      - node_modules:/app/node_modules
    environment:
      - SPACEX_API=
      - SPACEX_KEY=
      - DB_HOST=mongo
      - DB_NAME=admin
      - DB_USERNAME=admin
      - DB_PASSWORD=dzu7$2
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dzu7$2
      
volumes:
  node_modules:
    driver: local